### ISSUE TITLE
Generate PlantUML for headers in multple directories

### ISSUE THREAD

**Issue by swarajsomala** [thibaultmarin/hpp2plantuml#21]
Hello There,

It's a great tool to automate the generation of UML class diagrams from headers. Currently, in my project, I have several directories and each contains headers in the below format.

```
├── App
 |   └── App.h
├── Demo
│   └── Runtime.h
└── client
    ├── client.h
    ├── client_app.h


```

Is there any way to provide the root directory path to generate the PlantUML code?

**Comment by thibaultmarin** [comment]
Running `hpp2plantuml -i "*/*.h"` from the parent folder seems to work for me (we use glob to list files, see the glob documentation for details).
