### ISSUE TITLE
Class enumerator is not connecting

### ISSUE THREAD

**Issue by JacobNoergaard** [thibaultmarin/hpp2plantuml#27]
When creating an enumerator in a class it is not connecting correctly in the final diagram. An example is shown below.

```c++
class TestClass{
    int var1 = 10;
    int var2 = 10;

    void method1(int a, float b);
    void method2();

    enum class EnumTest{
        e_test1,
        e_test2
    };
};
```
This results in the following puml code. Is seems like the added "." in front of TestClass::EnumTest is making the arrow point back to "TestClass" instead of the enumerator. By removing the "." the enumerator is pointing correctly.

```puml
@startuml
/' Objects '/
class TestClass {
	-var1 : int
	-var2 : int
	-method1(int a, float b) : void
	-method2() : void
}

enum TestClass::EnumTest {
	e_test1
	e_test2
}
/' Inheritance relationships '/
/' Aggregation relationships '/
/' Nested objects '/
.TestClass +-- .TestClass::EnumTest
@enduml
```

![enum](https://user-images.githubusercontent.com/16765963/226273909-ac87b0f3-3024-401d-8078-4547b76fe7ac.png)

**Comment by thibaultmarin** [comment]
This seems fixed by the merge of #28.  Thanks.
