### ISSUE TITLE
Recommend you upgrade to our CppHeaderParser fork

### ISSUE THREAD

**Issue by virtuald** [thibaultmarin/hpp2plantuml#7]
In particular, I've overhauled significant pieces of the parser to support C++11 constructs.

https://github.com/robotpy/robotpy-cppheaderparser

**Comment by thibaultmarin** [comment]
Thanks, I will look into it.

**Comment by thibaultmarin** [comment]
v0.7 is now using robotpy-cppheaderparser, you could give it a try.
