### ISSUE TITLE
[Bug] The C++ class marked as delete shall not be presented in the class diagram

### ISSUE THREAD

**Issue by hysci** [thibaultmarin/hpp2plantuml#8]
Example:
class Foo
{
public:
    Foo& operator=(const Foo&) & = delete;
    Foo& operator=(Foo&&) & = delete;
}

These classes are deleted, but they are still listed in the PlantUML class diagram.

**Comment by thibaultmarin** [comment]
Thanks for the report.  It looks like this is going to have to wait until #7 is solved.

**Comment by thibaultmarin** [comment]
v0.7 should now handle the delete keyword.
