### ISSUE TITLE
Some diagram description contains errors

### ISSUE THREAD

**Issue by improve100** [thibaultmarin/hpp2plantuml#9]
java -jar ~/bin/plantuml.jar xsens.puml
Error line 5088 in file: xsens.puml
Some diagram description contains errors

Because github can't upload .puml file, i change suffix TXT.
[xsens.txt](https://github.com/thibaultmarin/hpp2plantuml/files/5853206/xsens.txt)

**Comment by thibaultmarin** [comment]
v0.7.1 tries to handle your example better.  It produces a valid plantuml file on my tests.  Please let me know if it works for you.
